[project]
name = "sas-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"  # Changed this line
dependencies = [
    "cashflower",
    "catboost",
    "lightgbm",
    "matplotlib",
    "numpy",
    "pandas",
    "scikit-learn",
    "seaborn",
    "tqdm",
    "xgboost",
]